'use strict';
const assert = require('node:assert/strict');
const { postPage } = require('../scripts/generate-blog');
const post = { slug: 'probe-post', title: 'Probe Title', description: 'Probe description', date: '2026-09-14', updated_at: '2026-10-06T12:00:00Z', tags: ['test'], html: '<p>Actual article body, available without JavaScript.</p>', wordCount: 8, readingMinutes: 1, max_comment_words: 2000 };
const html = postPage(post);
assert.ok(html.includes('id="postBody"'));
assert.ok(html.includes('id="postTitle">Probe Title</h1>'));
assert.ok(html.includes('Actual article body, available without JavaScript.'));
assert.ok(html.includes('<title>Probe Title — Hariom Lohar'));
assert.ok(html.includes('var POST_SLUG="probe-post"'));
assert.ok(html.includes('/api/blog/post?slug='), 'live refresh remains available');
assert.ok(!html.includes('Loading post from the database'));
const graph = JSON.parse(html.match(/<script[^>]*id="postStructuredData"[^>]*>([\s\S]*?)<\/script>/)[1]);
const article = graph['@graph'].find(n => n['@type'] === 'BlogPosting');
assert.equal(article.headline, post.title);
assert.equal(article.description, post.description);
assert.equal(article.dateModified, '2026-10-06T12:00:00.000Z');
assert.equal(article.mainEntityOfPage['@id'], 'https://hariomlohardev.github.io/blog/p/probe-post/#webpage');
assert.equal(graph['@graph'].find(n => n['@type'] === 'Person').image, 'https://hariomlohardev.github.io/assets/hariom-lohar.jpg');
